name: trading
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - build==1.3.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.61.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.44.0
      - matplotlib==3.10.7
      - numba==0.61.2
      - numpy==1.26.4
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - pandas-ta==0.4.71b0
      - patsy==1.0.2
      - pillow==12.0.0
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - six==1.17.0
      - statsmodels==0.14.5
      - ta==0.11.0
      - ta-lib==0.6.8
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - vtreat==1.3.1
      - xgboost==3.1.1
      - xlrd==2.0.2
prefix: /Users/zhiqiangz/miniconda3/envs/trading
